# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:latest

    environment:
      GO111MODULE: "on"
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go version

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go mod verify

      - run:
          name: "Fetch Go dependencies"
          command: |
            mage deps
            go get github.com/jstemmer/go-junit-report

      - run:
          name: "Run golint"
          command: |
            go get -u golang.org/x/lint/golint
            golint -set_exit_status ./...

      - run:
          name: "Run go vet"
          command: >
            go vet -v ./...

      - run:
          name: "Run unit tests"
          command: |
            trap "go-junit-report" <${TEST_RESULTS}/go-test.out > <${TEST_RESULTS}/go-test-report.xml EXIT
            mage test | tee ${TEST_RESULTS}/go-test.out

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
